### PR TITLE
Work in progress, opened for initial API review: streaming APIs

### PR DESCRIPTION
**Pull request by itamarst**
This is a sketch of a fix for #265.

This is an initial API review; basically it allows streaming data to and from file-like objects, which means memory usage can be fixed instead of `O(2N)` as it is now.

It should be completely backwards compatible: at the moment all but a single test pass. The new APIs are not tested yet, this is more of a sketch, although they are used somewhat.

If you're happy with this approach I can do further work to turn this into tested, documented code.

### CODE REVIEW

**Comment by itamarst** [comment]
@ionrock any thoughts?

**Comment by itamarst** [comment]
@ionrock just checking in again. I don't want to put too much effort into making this actually releasable (tests, docs, etc.) if you're not happy with the proposed API.

**Comment by ionrock** [comment]
@itamarst Thanks for digging into this. My only feedback is that changing the base cache seems pretty risky where it likely works well for a good majority of cases. I mentioned in my comment in #267 that it seems like we might want to focus on the serialization portion. For example, we're still calling serialize by default on the body in the `_cache_set` method, which seems like a good place to allow some logic to do the needful. I can imagine we could add a `body_handler` method to the BaseCache that when it exists is used in place of the serializer mechanics. That way you could take the body handler and save it in a file directly or whatever else (store in an object store for example). 

Let me know what you think or if you've run into issues that would not allow that to work. The handling of the body content has always been challenging, so it wouldn't surprise me if there are dragons in this tactic.

**Comment by itamarst** [comment]
The problem is you can't make memory usage constant without changing the base cache API. You could drop the serialization, yes, and then go from `O(2N)` to `O(N)`: instead of two copies of the body, the original and the serialized, you'd only have one. So a 400MB download will go from needing 800MB of RAM to 400MB of RAM. Which is still an improvement, but it's still not ideal, 400MB is still a lot, and who knows what size downloads people are actually using.

The proposed design would be `O(1)`, probably a very small constant depending what size chunks are being received from the HTTP server. Presumably less than 1MB of RAM.

But if you're not comfortable with changes on this scale I can switch to the `O(N)` solution, since it is still an improvement.

**Comment by itamarst** [comment]
Or. Hm. I guess given the `mmap` trick i might actually be possible to do `O(1)` memory usage if serialization goes away. It's a hack, but might work... let me think about it.

**Comment by itamarst** [comment]
So looking through what you wrote above... adding a `body_handler` to `BaseCache` is indeed necessary for this to work with constant memory usage, which _is_ possible with `mmap` hack. Downsides:

1. That's still a change to the base cache class.
2. You end up writing two copies of the file to disk, which is annoying when they're hundreds of MB.
3. The interface is a little wonky in that you have two calls to the cache, which as someone doing implementation means more work, you need to deal with the intermediate step in a more complex way (e.g. there's no exception handler for errors as there would be for a single method). In practice... probably not a big deal.

It is a smaller change to the base cache class, though, and likely to the code base in general...

**Comment by itamarst** [comment]
I think my design is better, but... the goal here is to optimize memory usage in one particular case, not to make this perfect, and current APIs work for most people I guess? So will try attempt that does something like this.

**Pull request closed without merging**
