### PR TITLE
apply heuristics more aggresively

### PR DESCRIPTION
**Pull request by eads**

### CODE REVIEW

**Comment by eads** [comment]
Whoops, I meant to put this in the PR description, but leaving it here now.

This is a possible solution to #123, though I think it needs some tests. 

I'm also curious if heuristics should apply to 301s as this PR would have it.

I'm also also curious if heuristics should apply even when method isn't GET, basically to give developers the maximum control over shaping the response that is sent for caching. That seems a little crazy but I figured it's at least worth asking.

My expectation with respect to heuristics was that they applied to any, or at least any cacheable, response.

**Comment by ionrock** [comment]
@eads I think this makes tons of sense. Can you add a test?

**Comment by eads** [comment]
I surely can. I should be able to get to this over the weekend. 

It seems like a good test would be one that replicates the bug when run against master and that passes with the PR. That's the direction I'll pursue unless you have other thoughts.

**Comment by eads** [comment]
Hey @ionrock! I wrote that patch. It tests cleanly in py 2.x but not in 3.x -- but the error seems like a bug in the test itself, or possibly even just a spurious error. It seems the test I added is somehow causing the CherryPy server used by the testing rig to choke. I'm curious if you have any insight.

Otherwise I feel pretty confident in this -- tests fail when patch isn't applied and pass when it is applied.

**Comment by eads** [comment]
Just a quick bump on this. I'm going to see if I can figure out what's up. We'd like to roll a final version of Elex by late July and this is one of the blockers. We can use a forked version as a dependency but that's no fun for anyone.

**Comment by ionrock** [comment]
@eads Ok, I think the error was just travis killing the cherrypy process when that was called. I'm going to merge and see if I can ensure the test doesn't keep failing.

**Comment by eads** [comment]
Huzzah! Any hunch as to why Travis was killing the cherrypy process? I couldn't find anything obvious in my tests that would cause a regression, but (far) stranger things have happened.

**Comment by eads** [comment]
Bummer, it doesn't seem to have been resolved. I can take a look at this next week if that would help.

**Pull request merged**
