### PR TITLE
adapater: recover from zlib.error.

### LINKED ISSUE #157: zlib incomplete or truncated stream
pypa/pip#4508

### PR DESCRIPTION
**Pull request by xoviat**
closes #157, pypa/pip#4508

### CODE REVIEW

**Comment by xoviat** [comment]
Yeah but you're not @ionrock .

**Comment by ionrock** [comment]
@xoviat Thanks!

**Comment by powersjcb** [comment]
I think this issue is still a blocker for pypa/pip #4639 until a new release version is tagged.

**Comment by ionrock** [comment]
@powersjcb I just pushed v0.12.4. Let me know if that works.

**Pull request merged**
